// Generated by gencpp from file task1/GetLocation.msg
// DO NOT EDIT!


#ifndef TASK1_MESSAGE_GETLOCATION_H
#define TASK1_MESSAGE_GETLOCATION_H

#include <ros/service_traits.h>


#include <task1/GetLocationRequest.h>
#include <task1/GetLocationResponse.h>


namespace task1
{

struct GetLocation
{

typedef GetLocationRequest Request;
typedef GetLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLocation
} // namespace task1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::task1::GetLocation > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::task1::GetLocation&) { return value(); }
};

template<>
struct DataType< ::task1::GetLocation > {
  static const char* value()
  {
    return "task1/GetLocation";
  }

  static const char* value(const ::task1::GetLocation&) { return value(); }
};


// service_traits::MD5Sum< ::task1::GetLocationRequest> should match 
// service_traits::MD5Sum< ::task1::GetLocation > 
template<>
struct MD5Sum< ::task1::GetLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::task1::GetLocation >::value();
  }
  static const char* value(const ::task1::GetLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::task1::GetLocationRequest> should match 
// service_traits::DataType< ::task1::GetLocation > 
template<>
struct DataType< ::task1::GetLocationRequest>
{
  static const char* value()
  {
    return DataType< ::task1::GetLocation >::value();
  }
  static const char* value(const ::task1::GetLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::task1::GetLocationResponse> should match 
// service_traits::MD5Sum< ::task1::GetLocation > 
template<>
struct MD5Sum< ::task1::GetLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::task1::GetLocation >::value();
  }
  static const char* value(const ::task1::GetLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::task1::GetLocationResponse> should match 
// service_traits::DataType< ::task1::GetLocation > 
template<>
struct DataType< ::task1::GetLocationResponse>
{
  static const char* value()
  {
    return DataType< ::task1::GetLocation >::value();
  }
  static const char* value(const ::task1::GetLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TASK1_MESSAGE_GETLOCATION_H
