// Generated by gencpp from file pck2/movesrvResponse.msg
// DO NOT EDIT!


#ifndef PCK2_MESSAGE_MOVESRVRESPONSE_H
#define PCK2_MESSAGE_MOVESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pck2
{
template <class ContainerAllocator>
struct movesrvResponse_
{
  typedef movesrvResponse_<ContainerAllocator> Type;

  movesrvResponse_()
    : return()  {
    }
  movesrvResponse_(const ContainerAllocator& _alloc)
    : return(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _return_type;
  _return_type return;





  typedef boost::shared_ptr< ::pck2::movesrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pck2::movesrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct movesrvResponse_

typedef ::pck2::movesrvResponse_<std::allocator<void> > movesrvResponse;

typedef boost::shared_ptr< ::pck2::movesrvResponse > movesrvResponsePtr;
typedef boost::shared_ptr< ::pck2::movesrvResponse const> movesrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pck2::movesrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pck2::movesrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pck2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pck2': ['/home/kikot/ROS/src/pck2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pck2::movesrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pck2::movesrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pck2::movesrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pck2::movesrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pck2::movesrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pck2::movesrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pck2::movesrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d02df2c0dff1a16a80230979e550820";
  }

  static const char* value(const ::pck2::movesrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d02df2c0dff1a16ULL;
  static const uint64_t static_value2 = 0xa80230979e550820ULL;
};

template<class ContainerAllocator>
struct DataType< ::pck2::movesrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pck2/movesrvResponse";
  }

  static const char* value(const ::pck2::movesrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pck2::movesrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string return\n\
\n\
";
  }

  static const char* value(const ::pck2::movesrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pck2::movesrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct movesrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pck2::movesrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pck2::movesrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "return: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.return);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCK2_MESSAGE_MOVESRVRESPONSE_H
