// Generated by gencpp from file pck2/movesrv.msg
// DO NOT EDIT!


#ifndef PCK2_MESSAGE_MOVESRV_H
#define PCK2_MESSAGE_MOVESRV_H

#include <ros/service_traits.h>


#include <pck2/movesrvRequest.h>
#include <pck2/movesrvResponse.h>


namespace pck2
{

struct movesrv
{

typedef movesrvRequest Request;
typedef movesrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct movesrv
} // namespace pck2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pck2::movesrv > {
  static const char* value()
  {
    return "a076d4040c3b13d43930b340985ffc25";
  }

  static const char* value(const ::pck2::movesrv&) { return value(); }
};

template<>
struct DataType< ::pck2::movesrv > {
  static const char* value()
  {
    return "pck2/movesrv";
  }

  static const char* value(const ::pck2::movesrv&) { return value(); }
};


// service_traits::MD5Sum< ::pck2::movesrvRequest> should match 
// service_traits::MD5Sum< ::pck2::movesrv > 
template<>
struct MD5Sum< ::pck2::movesrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pck2::movesrv >::value();
  }
  static const char* value(const ::pck2::movesrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pck2::movesrvRequest> should match 
// service_traits::DataType< ::pck2::movesrv > 
template<>
struct DataType< ::pck2::movesrvRequest>
{
  static const char* value()
  {
    return DataType< ::pck2::movesrv >::value();
  }
  static const char* value(const ::pck2::movesrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pck2::movesrvResponse> should match 
// service_traits::MD5Sum< ::pck2::movesrv > 
template<>
struct MD5Sum< ::pck2::movesrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pck2::movesrv >::value();
  }
  static const char* value(const ::pck2::movesrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pck2::movesrvResponse> should match 
// service_traits::DataType< ::pck2::movesrv > 
template<>
struct DataType< ::pck2::movesrvResponse>
{
  static const char* value()
  {
    return DataType< ::pck2::movesrv >::value();
  }
  static const char* value(const ::pck2::movesrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCK2_MESSAGE_MOVESRV_H
