// Generated by gencpp from file pck2/movesrvRequest.msg
// DO NOT EDIT!


#ifndef PCK2_MESSAGE_MOVESRVREQUEST_H
#define PCK2_MESSAGE_MOVESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pck2
{
template <class ContainerAllocator>
struct movesrvRequest_
{
  typedef movesrvRequest_<ContainerAllocator> Type;

  movesrvRequest_()
    : shape()
    , time(0)  {
    }
  movesrvRequest_(const ContainerAllocator& _alloc)
    : shape(_alloc)
    , time(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _shape_type;
  _shape_type shape;

   typedef int32_t _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::pck2::movesrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pck2::movesrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct movesrvRequest_

typedef ::pck2::movesrvRequest_<std::allocator<void> > movesrvRequest;

typedef boost::shared_ptr< ::pck2::movesrvRequest > movesrvRequestPtr;
typedef boost::shared_ptr< ::pck2::movesrvRequest const> movesrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pck2::movesrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pck2::movesrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pck2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'pck2': ['/home/kikot/ROS/src/pck2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pck2::movesrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pck2::movesrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pck2::movesrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pck2::movesrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pck2::movesrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pck2::movesrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pck2::movesrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4eb052c7f02dc3d6b175b629829c67f8";
  }

  static const char* value(const ::pck2::movesrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4eb052c7f02dc3d6ULL;
  static const uint64_t static_value2 = 0xb175b629829c67f8ULL;
};

template<class ContainerAllocator>
struct DataType< ::pck2::movesrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pck2/movesrvRequest";
  }

  static const char* value(const ::pck2::movesrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pck2::movesrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string shape\n\
int32 time\n\
";
  }

  static const char* value(const ::pck2::movesrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pck2::movesrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.shape);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct movesrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pck2::movesrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pck2::movesrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "shape: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.shape);
    s << indent << "time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCK2_MESSAGE_MOVESRVREQUEST_H
