// Generated by gencpp from file pck2/sum.msg
// DO NOT EDIT!


#ifndef PCK2_MESSAGE_SUM_H
#define PCK2_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <pck2/sumRequest.h>
#include <pck2/sumResponse.h>


namespace pck2
{

struct sum
{

typedef sumRequest Request;
typedef sumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sum
} // namespace pck2


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pck2::sum > {
  static const char* value()
  {
    return "eff151ed5a6df648d5c30ca5d71ccbda";
  }

  static const char* value(const ::pck2::sum&) { return value(); }
};

template<>
struct DataType< ::pck2::sum > {
  static const char* value()
  {
    return "pck2/sum";
  }

  static const char* value(const ::pck2::sum&) { return value(); }
};


// service_traits::MD5Sum< ::pck2::sumRequest> should match 
// service_traits::MD5Sum< ::pck2::sum > 
template<>
struct MD5Sum< ::pck2::sumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pck2::sum >::value();
  }
  static const char* value(const ::pck2::sumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pck2::sumRequest> should match 
// service_traits::DataType< ::pck2::sum > 
template<>
struct DataType< ::pck2::sumRequest>
{
  static const char* value()
  {
    return DataType< ::pck2::sum >::value();
  }
  static const char* value(const ::pck2::sumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pck2::sumResponse> should match 
// service_traits::MD5Sum< ::pck2::sum > 
template<>
struct MD5Sum< ::pck2::sumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pck2::sum >::value();
  }
  static const char* value(const ::pck2::sumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pck2::sumResponse> should match 
// service_traits::DataType< ::pck2::sum > 
template<>
struct DataType< ::pck2::sumResponse>
{
  static const char* value()
  {
    return DataType< ::pck2::sum >::value();
  }
  static const char* value(const ::pck2::sumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PCK2_MESSAGE_SUM_H
