// Generated by gencpp from file pck2/sumResponse.msg
// DO NOT EDIT!


#ifndef PCK2_MESSAGE_SUMRESPONSE_H
#define PCK2_MESSAGE_SUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pck2
{
template <class ContainerAllocator>
struct sumResponse_
{
  typedef sumResponse_<ContainerAllocator> Type;

  sumResponse_()
    : comment(0)  {
    }
  sumResponse_(const ContainerAllocator& _alloc)
    : comment(0)  {
  (void)_alloc;
    }



   typedef int32_t _comment_type;
  _comment_type comment;





  typedef boost::shared_ptr< ::pck2::sumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pck2::sumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sumResponse_

typedef ::pck2::sumResponse_<std::allocator<void> > sumResponse;

typedef boost::shared_ptr< ::pck2::sumResponse > sumResponsePtr;
typedef boost::shared_ptr< ::pck2::sumResponse const> sumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pck2::sumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pck2::sumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pck2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'pck2': ['/home/kikot/ROS/src/pck2/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pck2::sumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pck2::sumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pck2::sumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pck2::sumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pck2::sumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pck2::sumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pck2::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91e9f7dcfa8636513f40912ab8826294";
  }

  static const char* value(const ::pck2::sumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91e9f7dcfa863651ULL;
  static const uint64_t static_value2 = 0x3f40912ab8826294ULL;
};

template<class ContainerAllocator>
struct DataType< ::pck2::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pck2/sumResponse";
  }

  static const char* value(const ::pck2::sumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pck2::sumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 comment\n\
\n\
\n\
";
  }

  static const char* value(const ::pck2::sumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pck2::sumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.comment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pck2::sumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pck2::sumResponse_<ContainerAllocator>& v)
  {
    s << indent << "comment: ";
    Printer<int32_t>::stream(s, indent + "  ", v.comment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PCK2_MESSAGE_SUMRESPONSE_H
