// Generated by gencpp from file exercise6/GetLocation.msg
// DO NOT EDIT!


#ifndef EXERCISE6_MESSAGE_GETLOCATION_H
#define EXERCISE6_MESSAGE_GETLOCATION_H

#include <ros/service_traits.h>


#include <exercise6/GetLocationRequest.h>
#include <exercise6/GetLocationResponse.h>


namespace exercise6
{

struct GetLocation
{

typedef GetLocationRequest Request;
typedef GetLocationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLocation
} // namespace exercise6


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::exercise6::GetLocation > {
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::exercise6::GetLocation&) { return value(); }
};

template<>
struct DataType< ::exercise6::GetLocation > {
  static const char* value()
  {
    return "exercise6/GetLocation";
  }

  static const char* value(const ::exercise6::GetLocation&) { return value(); }
};


// service_traits::MD5Sum< ::exercise6::GetLocationRequest> should match 
// service_traits::MD5Sum< ::exercise6::GetLocation > 
template<>
struct MD5Sum< ::exercise6::GetLocationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::exercise6::GetLocation >::value();
  }
  static const char* value(const ::exercise6::GetLocationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise6::GetLocationRequest> should match 
// service_traits::DataType< ::exercise6::GetLocation > 
template<>
struct DataType< ::exercise6::GetLocationRequest>
{
  static const char* value()
  {
    return DataType< ::exercise6::GetLocation >::value();
  }
  static const char* value(const ::exercise6::GetLocationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::exercise6::GetLocationResponse> should match 
// service_traits::MD5Sum< ::exercise6::GetLocation > 
template<>
struct MD5Sum< ::exercise6::GetLocationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::exercise6::GetLocation >::value();
  }
  static const char* value(const ::exercise6::GetLocationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::exercise6::GetLocationResponse> should match 
// service_traits::DataType< ::exercise6::GetLocation > 
template<>
struct DataType< ::exercise6::GetLocationResponse>
{
  static const char* value()
  {
    return DataType< ::exercise6::GetLocation >::value();
  }
  static const char* value(const ::exercise6::GetLocationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXERCISE6_MESSAGE_GETLOCATION_H
